const health = [
  {
    name: "Vigor",
    type: "Health",
    isPassive: true,
    description: "Every time you are healed, you gain 1 extra health.",
    duration: null,
    icon: "vigor.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: null,
    value: 1,
    parentAbility: null,
  },
  {
    name: "Bandage",
    type: "Heal",
    isPassive: false,
    description: "Restores health to a target.",
    duration: null,
    icon: "heal.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 10,
    value: 2,
    parentAbility: "Vigor",
  },
  {
    name: "Enhanced-Vigor",
    type: "Health",
    isPassive: true,
    description: "Every time you are healed, you gain 3 extra health.",
    duration: null,
    icon: "vigor2.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: null,
    value: 3,
    parentAbility: "Vigor",
  },
  {
    name: "Superior-Vigor",
    type: "Health",
    isPassive: true,
    description: "Every time you are healed, you gain 5 extra health.",
    duration: null,
    icon: "vigor3.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: null,
    value: 5,
    parentAbility: "Enhanced-Vigor",
  },
];

const mana = [
  {
    name: "Arcane-Focus",
    type: "Wizard",
    isPassive: true,
    description: "Every time you gain mana, you gain 1 extra mana.",
    duration: null,
    icon: "mana-regen.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 50,
    value: 1,
    parentAbility: null,
  },
  {
    name: "Arcane-Recovery",
    type: "Wizard",
    isPassive: true,
    description: "Every time you gain mana, you gain 3 extra mana.",
    duration: null,
    icon: "mana-regen.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 50,
    value: 3,
    parentAbility: "Arcane-Focus",
  },
];

const trickery = [
  {
    name: "Evade",
    type: "Trickery",
    isPassive: false,
    description: "You may evade the effects of today's event.",
    duration: 20,
    icon: "evade.png",
    gemstoneCost: 2,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 50,
    value: null,
    parentAbility: null,
  },
  {
    name: "Twist-of-Fate",
    type: "Trickery",
    isPassive: false,
    description:
      "Roll a d6. On a 6, today's event is rerolled. You may only use this ability once per day.",
    duration: null,
    icon: "twist-of-fate.png",
    gemstoneCost: 2,
    manaCost: 4,
    healthCost: 0,
    xpGiven: 100,
    value: null,
    parentAbility: "Evade",
  },
  {
    name: "Postpone",
    type: "Trickery",
    isPassive: true,
    description: "You appeal to the game master, and plead for extended time.",
    duration: 60,
    icon: "postpone.png",
    gemstoneCost: 2,
    manaCost: 10,
    healthCost: 0,
    xpGiven: 50,
    value: null,
    parentAbility: "Evade",
  },
];

const adventurer = [
  {
    name: "Adventurer",
    type: "Adventurer",
    isPassive: true,
    description: "Allows participation in the arena's games.",
    duration: null,
    icon: "adventurer.png",
    gemstoneCost: 1,
    manaCost: 0,
    healthCost: 0,
    xpGiven: 50,
    value: null,
    parentAbility: null,
  },
  {
    name: "Economist",
    type: "Adventurer",
    isPassive: true,
    description:
      "Every time you gain xp, you gain the same amount of gold. Gold can be spent in the shop.",
    duration: null,
    icon: "economist.png",
    gemstoneCost: 1,
    manaCost: 0,
    healthCost: 0,
    xpGiven: 50,
    value: null,
    parentAbility: "Adventurer",
  },
];

const wizard = [
  {
    name: "Arcane-Gift",
    type: "Wizard",
    isPassive: true,
    description:
      "Every time you gain mana, you gain 1 extra mana. This ability stacks.",
    duration: null,
    icon: "mana-regen.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 50,
    value: 1,
    parentAbility: null,
  },
  {
    name: "Essence-Transfer",
    type: "Wizard",
    isPassive: false,
    description: "You may give 2 of your mana to another player.",
    duration: null,
    icon: "mana-regen.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 20,
    value: 2,
    parentAbility: "Arcane-Gift",
  },
];

const druid = [
  {
    name: "Heal",
    type: "Druid",
    isPassive: false,
    description: "Restores health to a target.",
    duration: null,
    icon: "heal.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 10,
    value: 4,
    parentAbility: null,
  },
  {
    name: "Greater-Heal",
    type: "Druid",
    isPassive: false,
    description: "Restores a large amount of health to a target.",
    duration: null,
    icon: "heal2.png",
    gemstoneCost: 1,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 15,
    value: 6,
    parentAbility: "Heal",
  },
  {
    name: "Superior-Heal",
    type: "Druid",
    isPassive: false,
    description: "Restores a great amount of health to a target.",
    duration: null,
    icon: "heal3.png",
    gemstoneCost: 2,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 20,
    value: 8,
    parentAbility: "Greater-Heal",
  },
  {
    name: "Healing-aura",
    type: "Druid",
    isPassive: false,
    description: "Restores health to all guildmembers.",
    duration: null,
    icon: "healingAura.png",
    gemstoneCost: 2,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 50,
    value: 3,
    parentAbility: "Greater-Heal",
  },
  {
    name: "Revive",
    type: "Druid",
    isPassive: false,
    description:
      "Revives a target from death. Must be done before a game master revives the target.",
    duration: null,
    icon: "revive.png",
    gemstoneCost: 2,
    manaCost: 2,
    healthCost: 0,
    xpGiven: 100,
    value: null,
    parentAbility: "Superior-Heal",
  },
];

const barbarian = [
  {
    name: "Toughness",
    type: "Barbarian",
    isPassive: true,
    description: "You gain 5 extra health.",
    duration: null,
    icon: "toughness.png",
    gemstoneCost: 1,
    manaCost: null,
    healthCost: 0,
    xpGiven: 50,
    value: null,
    parentAbility: null,
  },
  {
    name: "Shield",
    type: "Barbarian",
    isPassive: true,
    description: "You block 2 damage from all attacks.",
    duration: null,
    icon: "shield.png",
    gemstoneCost: 2,
    manaCost: null,
    healthCost: 0,
    xpGiven: 50,
    value: 2,
    parentAbility: "Toughness",
  },
  {
    name: "Bloodgift",
    type: "Barbarian",
    isPassive: false,
    description: "You may trade 5 health for 2 mana.",
    duration: null,
    icon: "bloodlust.png",
    gemstoneCost: 1,
    manaCost: 0,
    healthCost: 5,
    xpGiven: 50,
    value: 2,
    parentAbility: "Toughness",
  },
  {
    name: "Blood-bond",
    type: "Barbarian",
    isPassive: false,
    description: "You may give 5 health to another player.",
    duration: null,
    icon: "bloodbond.png",
    gemstoneCost: 2,
    manaCost: 0,
    healthCost: 5,
    xpGiven: 50,
    value: 5,
    parentAbility: "Bloodlust",
  },
  {
    name: "Enhanced-Toughness",
    type: "Barbarian",
    isPassive: true,
    description: "You gain 10 extra health.",
    duration: null,
    icon: "toughness2.png",
    gemstoneCost: 1,
    manaCost: null,
    healthCost: 0,
    xpGiven: 50,
    value: null,
    parentAbility: "Shield",
  },
  {
    name: "Superior-Toughness",
    type: "Barbarian",
    isPassive: true,
    description: "You gain 15 extra health.",
    duration: null,
    icon: "toughness3.png",
    gemstoneCost: 1,
    manaCost: null,
    healthCost: 0,
    xpGiven: 50,
    value: null,
    parentAbility: "Enhanced-Toughness",
  },
];

const abilities = [
  ...health,
  ...mana,
  ...trickery,
  ...adventurer,
  ...wizard,
  ...druid,
  ...barbarian,
];
export default abilities;
