const cosmic = [
  {
    name: "Poor-Harvest",
    description: "Everyone gains 1 XP",
    // presetDate: "",
    frequency: 10,
    automatic: true,
    blockAbilityType: null,
    triggerAtNoon: true,
    grantAbility: false,
    abilityName: "Poor-Harvest",
  },
  {
    name: "Troubled-Waters",
    description:
      "A storm is crashing down upon us. All take 5 damage. No healing may occur today.",
    // presetDate: "",
    frequency: 10,
    automatic: true,
    blockAbilityType: "Heal",
    triggerAtNoon: true,
    grantAbility: false,
    abilityName: "Troubled-Waters",
  },
  {
    name: "You-know-nothing-about-Snow",
    description: "If it is snowing outside, everyone gains 100 XP.",
    // presetDate: "",
    frequency: 5,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "Hot-like-a-furnace",
    description:
      "All students wearing outerwear jackets the first time this event is revealed, loses 5 hp.",
    // presetDate: "",
    frequency: 15,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "Nei-nei-gutt",
    description:
      "All students wearing headwear the first time this event is revealed, loses 5 HP.",
    // presetDate: "",
    frequency: 15,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "Janteloven",
    description: "The player with the most XP in each guild loses 5 HP.",
    // presetDate: "",
    frequency: 5,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "Rock of Ages!",
    description:
      "All guilds must play rock paper scissors against eachother. The winner on each guild gains 100 XP and advances to a final round, where the winner (in each class) replenishes all HP.",
    // presetDate: "",
    frequency: 10,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "Winter-Is-Coming",
    description:
      "Summer children (born between 14.04 and 13.10) loses 5 HP. Winter children (born between 14.10 and 13.04) gains 100 XP.",
    // presetDate: "",
    frequency: 10,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "Shadowlands",
    description: "Lights must be turned off for the next seven minutes.",
    // presetDate: "",
    frequency: 5,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "Dangeorus-Raid",
    description:
      "Every student rolls a D6. Any student who rolls a 6, gains 100 XP and may heal up to 5 HP. Any student who rolls a 1, loses 7 HP.",
    // presetDate: "",
    frequency: 5,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "Sacrificial-Lamb",
    description:
      "You may sacrifice HP for XP today. For every 5 HP you sacrifice you gain 100 XP. '",
    // presetDate: "",
    frequency: 15,
    automatic: true,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: true,
    abilityName: "Sacrificial-Lamb",
  },
  {
    name: "",
    description: "",
    // presetDate: "",
    frequency: 5,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "",
    description: "",
    // presetDate: "",
    frequency: 5,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "",
    description: "",
    // presetDate: "",
    frequency: 5,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
  {
    name: "",
    description: "",
    // presetDate: "",
    frequency: 5,
    automatic: false,
    blockAbilityType: null,
    triggerAtNoon: false,
    grantAbility: false,
    abilityName: null,
  },
];

const abilities = [...cosmic];
export default abilities;
