const shopItems = [
  {
    id: 1,
    name: "Peasant",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 2,
    classReq: null,
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 2,
    name: "Apprentice",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 4,
    classReq: null,
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 3,
    name: "Mystic",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 6,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 4,
    name: "Magical",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 5,
    name: "Stormcaller",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 6,
    name: "Lover of fine arts",
    description: null,
    price: 8000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 7,
    name: "Nerd",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 8,
    name: "Geek",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 9,
    name: "Weeb",
    description: null,
    price: 12000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 10,
    name: "Cat person",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 11,
    name: "Dog person",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 12,
    name: "Kali",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 13,
    name: "Mint",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 14,
    name: "Ubuntu",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 15,
    name: "Arch",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 16,
    name: "Debian",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 17,
    name: "Windows",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 18,
    name: "Beast",
    description: null,
    price: 10000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 19,
    name: "Script Kiddie",
    description: null,
    price: 12000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 20,
    name: "Firefox",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 21,
    name: "Chrome",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 22,
    name: "Brave",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 23,
    name: "Safari",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 24,
    name: "Archmage",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 25,
    name: "Shadowmancer",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 17,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 26,
    name: "Elder Guardian",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 20,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 27,
    name: "Great wise one",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 25,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 28,
    name: "Grandmaster",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 25,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 29,
    name: "Legend",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 35,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 30,
    name: "Archon",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 45,
    classReq: null,
    specialReq: null,
    rarity: "Legendary",
  },
  {
    id: 50,
    name: "Immortal",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 50,
    classReq: null,
    specialReq: null,
    rarity: "Legendary",
  },
  {
    id: 51,
    name: "Divine",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 60,
    classReq: null,
    specialReq: null,
    rarity: "Legendary",
  },
  {
    id: 31,
    name: "Demigod",
    description: null,
    price: 99000,
    type: "Title",
    levelReq: 65,
    classReq: null,
    specialReq: null,
    rarity: "Mythic",
  },
  {
    id: 32,
    name: "HACKER",
    description: "Granted for participating in the CTF",
    price: 0,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: "ctf",
    rarity: "Epic",
  },
  {
    id: 33,
    name: "HACKER GOD",
    description: "Granted for winning the CTF",
    price: 0,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: "ctf-winner",
    rarity: "Mythic",
  },
  {
    id: 34,
    name: "King",
    description: "Granted for being on the student council",
    price: 0,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: "king",
    rarity: "Legendary",
  },
  {
    id: 35,
    name: "Queen",
    description: "Granted for being on the student council",
    price: 0,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: "queen",
    rarity: "Legendary",
  },
  {
    id: 36,
    name: "Virtual Wizard",
    description:
      "Gain permanent access to a Virtual Machine in the computer lab",
    price: 40000,
    type: "Badge",
    levelReq: 10,
    classReq: null,
    specialReq: "vm",
    rarity: "Rare",
  },
  {
    id: 37,
    name: "Installation Wizard",
    description: "Gain permanent access to a computer in the computer lab",
    price: 50000,
    type: "Badge",
    levelReq: 20,
    classReq: null,
    specialReq: "computer",
    rarity: "Epic",
  },
  {
    id: 38,
    name: "Lab Assistant",
    description: "Gain an access card to the computer lab",
    price: 50000,
    type: "Badge",
    levelReq: 25,
    classReq: null,
    specialReq: "lab",
    rarity: "Legendary",
  },
  {
    id: 39,
    name: "Maker",
    description: "Gain an access card to MakerSpace",
    price: 50000,
    type: "Badge",
    levelReq: 25,
    classReq: null,
    specialReq: "maker",
    rarity: "Legendary",
  },
  {
    id: 40,
    name: "The Switcher",
    description: "Gain access to the Nintendo Switch during breaks",
    price: 10000,
    type: "Badge",
    levelReq: 7,
    classReq: null,
    specialReq: "nintendo",
    rarity: "Epic",
  },
  {
    id: 41,
    name: "The Player",
    description: "Gain access to the PlayStation 5 during breaks",
    price: 10000,
    type: "Badge",
    levelReq: 7,
    classReq: null,
    specialReq: "playstation",
    rarity: "Epic",
  },
  {
    id: 42,
    name: "Bugfinder",
    description: "Found a bug in TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "bug",
    rarity: "Rare",
  },
  {
    id: 43,
    name: "Master of bugs",
    description: "Found a great number of bugs in TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "bugmaster",
    rarity: "Epic",
  },
  {
    id: 44,
    name: "Exterminator",
    description: "Found and fixed a bug in TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "bugfixer",
    rarity: "Legendary",
  },
  {
    id: 45,
    name: "Alpha Tester",
    description: "Tested TillerQuest while it was in alpha development",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "alpha",
    rarity: "Legendary",
  },
  {
    id: 46,
    name: "Beta Tester",
    description: "Tested TillerQuest while it was in beta development",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "beta",
    rarity: "Epic",
  },
  {
    id: 47,
    name: "Game Master",
    description: "Available to all GMs",
    price: 2147483647, // The maximum value for a 32-bit signed integer
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "gm",
    rarity: "Mythic",
  },
  {
    id: 48,
    name: "Developer",
    description: "Helped with the development of TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "dev",
    rarity: "Mythic",
  },
  {
    id: 49,
    name: "Artist",
    description: "Created art for TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "artist",
    rarity: "Epic",
  },
  // 50
  // 51
  {
    id: 52,
    name: "Chosen Champion",
    description:
      "Entrusted with maintaining the lab servers by the game masters",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "champion",
    rarity: "Mythic",
  },
];

export default shopItems;
