const users = [
  {
    name: "Peasant",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 2,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Apprentice",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 4,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Mystic",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 6,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Magical",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Stormcaller",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Lover of fine arts",
    description: null,
    price: 8000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Nerd",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Geek",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Weeb",
    description: null,
    price: 12000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Cat person",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Dog person",
    description: null,
    price: 3000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Beast",
    description: null,
    price: 10000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
  },
  {
    name: "HACKZOR",
    description: null,
    price: 12000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Archmage",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Shadowmancer",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 17,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Elder Guardian",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 20,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Great wise one",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 22,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Archon",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 25,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Mini-GM",
    description: null,
    price: 25000,
    type: "Title",
    levelReq: 30,
    classReq: null,
    specialReq: null,
  },
  {
    name: "Hackerman",
    description: "Granted for participating in the CTF",
    price: 0,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: "ctf",
  },
  {
    name: "HACKER GOD",
    description: "Granted for winning the CTF",
    price: 0,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: "ctf-winner",
  },
  {
    name: "King",
    description: "Granted for being on the student council",
    price: 0,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: "student-council",
  },
  {
    name: "Queen",
    description: "Granted for being on the student council",
    price: 0,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: "student-council",
  },
  {
    name: "Installation Wizard",
    description: "Gain permanent access to a computer in the computer lab",
    price: 30000,
    type: "Access",
    levelReq: 10,
    classReq: null,
    specialReq: "trusted",
  },
  {
    name: "Lab Assistant",
    description: "Gain a card to the computer lab",
    price: 30000,
    type: "Access",
    levelReq: 15,
    classReq: null,
    specialReq: "trusted",
  },
  {
    name: "Maker",
    description: "Gain a card to MakerSpace",
    price: 30000,
    type: "Access",
    levelReq: 15,
    classReq: null,
    specialReq: "trusted",
  },
];

export default users;
