const users = [
  {
    id: "99991",
    username: "Ymir",
    name: "Snow",
    lastname: "Dog",
    email: "john@example.com",
    image: "Druid1",
    hp: 88,
    hpMax: 100,
    mana: 37,
    manaMax: 50,
    level: 10,
    guildName: "Testers",
    role: "USER",
    class: "Druid",
  },
  {
    id: "99992",
    username: "Button",
    name: "Benja",
    lastname: "Min",
    email: "karl@example.com",
    image: "Barbarian1",
    hp: 44,
    hpMax: 100,
    mana: 20,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    role: "USER",
    class: "Barbarian",
  },
  {
    id: "99993",
    username: "Karl",
    name: "Karld",
    lastname: "Kai",
    email: "kai@example.com",
    image: "BloodMage1",
    hp: 10,
    hpMax: 100,
    mana: 20,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    role: "USER",
    class: "BloodMage",
  },
  {
    id: "99994",
    username: "OlaLANGTNAVNmedMANGEtegn",
    name: "olafortsattLangtNavn",
    lastname: "VELDIGLANGTNAVN",
    email: "ola@example.com",
    image: "Wizard2",
    hp: 33,
    hpMax: 100,
    mana: 20,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    role: "USER",
    class: "Wizard",
  },
];

export default users;
