const users = [
  {
    id: "99991",
    username: "Ymir",
    name: "Snow",
    lastname: "Dog",
    email: "john@example.com",
    image: "Druid1",
    hp: 88,
    hpMax: 100,
    mana: 37,
    manaMax: 50,
    level: 10,
    guildName: "Testers",
    role: "USER",
    class: "Druid",
  },
  {
    id: "99992",
    username: "Button",
    name: "Benja",
    lastname: "Min",
    email: "karl@example.com",
    image: "Barbarian1",
    hp: 44,
    hpMax: 100,
    mana: 20,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    role: "USER",
    class: "Barbarian",
  },
  {
    id: "99993",
    username: "Karl",
    name: "Karld",
    lastname: "Kai",
    email: "kai@example.com",
    image: "BloodMage1",
    hp: 10,
    hpMax: 100,
    mana: 20,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    role: "USER",
    class: "BloodMage",
  },
  {
    id: "99994",
    username: "OlaLANGTNAVN123",
    name: "OlaLANGTNAVN123",
    lastname: "OlaLANGTNAVN123",
    email: "ola@example.com",
    image: "Wizard2",
    hp: 33,
    hpMax: 100,
    mana: 20,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    role: "USER",
    class: "Wizard",
  },
  {
    id: "99995",
    username: "dawdawdwad",
    name: "adwdawdawd",
    lastname: "adwdawdawd",
    email: "ola@example.com",
    image: "Wizard2",
    hp: 33,
    hpMax: 100,
    mana: 20,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    schoolClass: "Class_1IM4",
    role: "USER",
    class: "Wizard",
  },
  {
    id: "99996",
    username: "Luna1IM4",
    name: "Luna",
    lastname: "Moon",
    email: "luna@example.com",
    image: "Druid2",
    hp: 70,
    hpMax: 100,
    mana: 30,
    manaMax: 50,
    level: 7,
    guildName: "Testers",
    schoolClass: "Class_1IM4",
    role: "USER",
    class: "Druid",
  },
  {
    id: "99997",
    username: "Rex1IM4",
    name: "Rex",
    lastname: "Stone",
    email: "rex@example.com",
    image: "Barbarian2",
    hp: 90,
    hpMax: 100,
    mana: 15,
    manaMax: 50,
    level: 6,
    guildName: "Testers",
    schoolClass: "Class_1IM4",
    role: "USER",
    class: "Barbarian",
  },
  {
    id: "99998",
    username: "Mira1IM4",
    name: "Mira",
    lastname: "Sky",
    email: "mira@example.com",
    image: "Wizard3",
    hp: 60,
    hpMax: 100,
    mana: 40,
    manaMax: 50,
    level: 9,
    guildName: "Testers",
    schoolClass: "Class_1IM4",
    role: "USER",
    class: "Wizard",
  },
  {
    id: "99999",
    username: "Finn1IM4",
    name: "Finn",
    lastname: "Lake",
    email: "finn@example.com",
    image: "BloodMage2",
    hp: 25,
    hpMax: 100,
    mana: 35,
    manaMax: 50,
    level: 7,
    guildName: "Testers",
    schoolClass: "Class_1IM4",
    role: "USER",
    class: "BloodMage",
  },
  {
    id: "100000",
    username: "Sage1IM4",
    name: "Sage",
    lastname: "Leaf",
    email: "sage@example.com",
    image: "Druid3",
    hp: 80,
    hpMax: 100,
    mana: 25,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    schoolClass: "Class_1IM4",
    role: "USER",
    class: "Druid",
  },
  {
    id: "100001",
    username: "Blaze1IM4",
    name: "Blaze",
    lastname: "Fire",
    email: "blaze@example.com",
    image: "Barbarian3",
    hp: 55,
    hpMax: 100,
    mana: 18,
    manaMax: 50,
    level: 6,
    guildName: "Testers",
    schoolClass: "Class_1IM4",
    role: "USER",
    class: "Barbarian",
  },
  {
    id: "100002",
    username: "Nova1IM4",
    name: "Nova",
    lastname: "Star",
    email: "nova@example.com",
    image: "Wizard4",
    hp: 48,
    hpMax: 100,
    mana: 45,
    manaMax: 50,
    level: 9,
    guildName: "Testers",
    schoolClass: "Class_1IM4",
    role: "USER",
    class: "Wizard",
  },
  {
    id: "100003",
    username: "Ava2IT1",
    name: "Ava",
    lastname: "Stone",
    email: "ava2it1@example.com",
    image: "Druid4",
    hp: 85,
    hpMax: 100,
    mana: 32,
    manaMax: 50,
    level: 7,
    guildName: "Testers",
    schoolClass: "Class_2IT1",
    role: "USER",
    class: "Druid",
  },
  {
    id: "100004",
    username: "Leo2IT1",
    name: "Leo",
    lastname: "Wolf",
    email: "leo2it1@example.com",
    image: "Barbarian4",
    hp: 60,
    hpMax: 100,
    mana: 22,
    manaMax: 50,
    level: 6,
    guildName: "Testers",
    schoolClass: "Class_2IT1",
    role: "USER",
    class: "Barbarian",
  },
  {
    id: "100005",
    username: "Ella2IT1",
    name: "Ella",
    lastname: "Rain",
    email: "ella2it1@example.com",
    image: "Wizard5",
    hp: 50,
    hpMax: 100,
    mana: 48,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    schoolClass: "Class_2IT1",
    role: "USER",
    class: "Wizard",
  },
  {
    id: "100006",
    username: "Max2IT1",
    name: "Max",
    lastname: "Hill",
    email: "max2it1@example.com",
    image: "BloodMage3",
    hp: 30,
    hpMax: 100,
    mana: 38,
    manaMax: 50,
    level: 7,
    guildName: "Testers",
    schoolClass: "Class_2IT1",
    role: "USER",
    class: "BloodMage",
  },
  {
    id: "100007",
    username: "Zoe2IT1",
    name: "Zoe",
    lastname: "Sun",
    email: "zoe2it1@example.com",
    image: "Druid5",
    hp: 78,
    hpMax: 100,
    mana: 29,
    manaMax: 50,
    level: 6,
    guildName: "Testers",
    schoolClass: "Class_2IT1",
    role: "USER",
    class: "Druid",
  },
  {
    id: "100008",
    username: "Jack2IT1",
    name: "Jack",
    lastname: "Storm",
    email: "jack2it1@example.com",
    image: "Barbarian5",
    hp: 92,
    hpMax: 100,
    mana: 17,
    manaMax: 50,
    level: 7,
    guildName: "Testers",
    schoolClass: "Class_2IT1",
    role: "USER",
    class: "Barbarian",
  },
  {
    id: "100009",
    username: "Mia2IT1",
    name: "Mia",
    lastname: "Sky",
    email: "mia2it1@example.com",
    image: "Wizard6",
    hp: 62,
    hpMax: 100,
    mana: 41,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    schoolClass: "Class_2IT1",
    role: "USER",
    class: "Wizard",
  },
  {
    id: "100010",
    username: "Ben2IT1",
    name: "Ben",
    lastname: "Lake",
    email: "ben2it1@example.com",
    image: "BloodMage4",
    hp: 28,
    hpMax: 100,
    mana: 36,
    manaMax: 50,
    level: 6,
    guildName: "Testers",
    schoolClass: "Class_2IT1",
    role: "USER",
    class: "BloodMage",
  },
];

export default users;
