const users = [
  {
    id: "99991",
    username: "Ymir",
    name: "Snow",
    lastname: "Dog",
    email: "john@example.com",
    image: "Druid1",
    hp: 88,
    hpMax: 100,
    mana: 37,
    manaMax: 50,
    level: 10,
    guildName: "Testers",
    role: "USER",
    class: "Druid",
  },
  {
    id: "99992",
    username: "Button",
    name: "Benja",
    lastname: "Min",
    email: "karl@example.com",
    image: "Barbarian1",
    hp: 44,
    hpMax: 100,
    mana: 20,
    manaMax: 50,
    level: 8,
    guildName: "Testers",
    role: "USER",
    class: "Barbarian",
  },
];

export default users;
