interface ShopItems {
  id: number;
  name: string;
  description: string | null; // optional, can be null if no description
  icon?: string; // optional
  price: number; // in gold
  currency?: "GOLD" | "GEMSTONES"; // currency type. Default is GOLD
  type: "Title" | "Badge" | "Object" | "DiceColorset"; // type of the item
  levelReq: number | null; // level requirement, can be null if no requirement
  classReq: string | null; // class requirement
  specialReq: string | null; // special requirement, can be null if no requirement
  gemstonesSpentReq?: number | null; // requirement for gemstones spent in shop
  rarity: "Common" | "Uncommon" | "Rare" | "Epic" | "Legendary" | "Mythic"; // rarity of the item
}

const shopItems: ShopItems[] = [
  {
    id: 1,
    name: "Peasant",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 2,
    classReq: null,
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 2,
    name: "Apprentice",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 4,
    classReq: null,
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 3,
    name: "Mystic",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 6,
    classReq: null,
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 53,
    name: "Aspiring Hero",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 4,
    name: "Magical",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 5,
    name: "Stormcaller",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 6,
    name: "Lover Of Fine Arts",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 7,
    name: "Nerd",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 8,
    name: "Geek",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 9,
    name: "Weeb",
    description: null,
    price: 10000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 10,
    name: "Cat",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 8,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 11,
    name: "Dog",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: 8,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 12,
    name: "Kali",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 13,
    name: "Mint",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 14,
    name: "Ubuntu",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 15,
    name: "Arch",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 16,
    name: "Debian",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 17,
    name: "Windows",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 18,
    name: "Beast",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 19,
    name: "Script Kiddie",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 20,
    name: "Firefox",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 21,
    name: "Chrome",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 22,
    name: "Brave",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 23,
    name: "Safari",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 24,
    name: "Archmage",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 25,
    name: "Shadowmancer",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 17,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 26,
    name: "Elder Guardian",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 20,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 27,
    name: "Great Wise One",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 25,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 28,
    name: "Grandmaster",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 30,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 29,
    name: "Legend",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 35,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 30,
    name: "Divine",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 45,
    classReq: null,
    specialReq: null,
    rarity: "Epic",
  },
  {
    id: 50,
    name: "Immortal",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 50,
    classReq: null,
    specialReq: null,
    rarity: "Legendary",
  },
  {
    id: 51,
    name: "Archon",
    description: null,
    price: 0,
    type: "Title",
    levelReq: 60,
    classReq: null,
    specialReq: null,
    rarity: "Legendary",
  },
  {
    id: 31,
    name: "Demigod",
    description: null,
    price: 200000,
    type: "Title",
    levelReq: 70,
    classReq: null,
    specialReq: null,
    rarity: "Legendary",
  },
  {
    id: 32,
    name: "HACKER",
    description: "Granted for participating in the CTF",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    specialReq: "ctf",
    icon: "ctf",
    rarity: "Legendary",
  },
  {
    id: 33,
    name: "HACKER GOD",
    description: "Granted for winning the CTF",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "ctf-winner",
    specialReq: "ctf-winner",
    rarity: "Mythic",
  },
  {
    id: 34,
    name: "King",
    description: "Granted for being on the student council",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "king",
    specialReq: "king",
    rarity: "Legendary",
  },
  {
    id: 35,
    name: "Queen",
    description: "Granted for being on the student council",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "queen",
    specialReq: "queen",
    rarity: "Legendary",
  },
  {
    id: 36,
    name: "Virtual Wizard",
    description:
      "Gain permanent access to a Virtual Machine in the computer lab",
    price: 40000,
    type: "Badge",
    levelReq: 10,
    classReq: null,
    icon: "vm",
    specialReq: "vm",
    rarity: "Rare",
  },
  {
    id: 37,
    name: "Installation Wizard",
    description: "Gain permanent access to a computer in the computer lab",
    price: 50000,
    type: "Badge",
    levelReq: 20,
    classReq: null,
    icon: "computer",
    specialReq: "computer",
    rarity: "Epic",
  },
  {
    id: 38,
    name: "Lab Assistant",
    description: "Gain an access card to the computer lab",
    price: 100000,
    type: "Badge",
    levelReq: 25,
    classReq: null,
    icon: "lab",
    specialReq: "lab",
    rarity: "Legendary",
  },
  {
    id: 39,
    name: "Maker",
    description: "Gain an access card to MakerSpace",
    price: 75000,
    type: "Badge",
    levelReq: 25,
    classReq: null,
    icon: "maker",
    specialReq: "maker",
    rarity: "Legendary",
  },
  {
    id: 40,
    name: "The Switcher",
    description: "Gain access to the Nintendo Switch during breaks",
    price: 10000,
    type: "Badge",
    levelReq: 7,
    classReq: null,
    icon: "nintendo",
    specialReq: "nintendo",
    rarity: "Epic",
  },
  {
    id: 41,
    name: "The Player",
    description: "Gain access to the PlayStation 5 during breaks",
    price: 10000,
    type: "Badge",
    levelReq: 7,
    classReq: null,
    icon: "playstation",
    specialReq: "playstation",
    rarity: "Epic",
  },
  {
    id: 42,
    name: "Bugfinder",
    description: "Found a bug in TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "bug",
    specialReq: "bug",
    rarity: "Rare",
  },
  {
    id: 43,
    name: "Master Of Bugs",
    description: "Found a great number of bugs in TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "bugmaster",
    specialReq: "bugmaster",
    rarity: "Epic",
  },
  {
    id: 44,
    name: "Exterminator",
    description: "Found and fixed a bug in TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "bugfixer",
    specialReq: "bugfixer",
    rarity: "Legendary",
  },
  {
    id: 45,
    name: "Alpha Tester",
    description: "Tested TillerQuest while it was in alpha development",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "alpha",
    specialReq: "alpha",
    rarity: "Legendary",
  },
  {
    id: 46,
    name: "Beta Tester",
    description: "Tested TillerQuest while it was in beta development",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "beta",
    specialReq: "beta",
    rarity: "Epic",
  },
  {
    id: 47,
    name: "Game Master",
    description: "Available to all GMs",
    price: 2147483647, // The maximum value for a 32-bit signed integer
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "gm",
    specialReq: "gm",
    rarity: "Mythic",
  },
  {
    id: 48,
    name: "Developer",
    description: "Helped with the development of TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "dev",
    specialReq: "dev",
    rarity: "Mythic",
  },
  {
    id: 49,
    name: "Artist",
    description: "Created art for TillerQuest",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "artist",
    specialReq: "artist",
    rarity: "Epic",
  },
  {
    id: 50,
    name: "Cyberpunk",
    description: "Participated in a CTF event outside of Tiller.",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "cyberpunk",
    specialReq: "cyberpunk",
    rarity: "Legendary",
  },
  {
    id: 51,
    name: "Heimdallsquester",
    description:
      "Was a player in the original game that TillerQuest originated from.",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "heimdallsquest",
    specialReq: "heimdallsquest",
    rarity: "Legendary",
  },
  {
    id: 52,
    name: "Chosen Champion",
    description:
      "Entrusted by the Game Masters with the glorious honor of maintaining the lab servers.",
    price: 0,
    type: "Badge",
    levelReq: null,
    classReq: null,
    icon: "champion",
    specialReq: "champion",
    rarity: "Mythic",
  },
  {
    id: 53,
    name: "Square Eyed",
    description: "Gain a better monitor for use in the computer lab.",
    price: 75000,
    type: "Object",
    levelReq: 40,
    classReq: null,
    icon: "screen",
    specialReq: "screen",
    rarity: "Epic",
  },
  {
    id: 54,
    name: "Debugging Duck",
    description:
      "A special rubber duck that helps you debug your code. Yours to keep - forever judging your horrible coding practices.",
    price: 200000,
    type: "Object",
    levelReq: null,
    classReq: null,
    icon: "rubberduck",
    specialReq: "rubberduck",
    rarity: "Mythic",
  },
  {
    id: 55,
    name: "Java Warrior",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 56,
    name: "Python Sage",
    description: null,
    price: 2000,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: null,
    rarity: "Uncommon",
  },
  {
    id: 57,
    name: "Javascript Ninja",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 58,
    name: "TypeScript Samurai",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 59,
    name: "C# Sorcerer",
    description: "My optometrist says i c#",
    price: 5000,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 60,
    name: "Rusty Crab",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 61,
    name: "Assembly Chad",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 62,
    name: "C++ Warlock",
    description: null,
    price: 5000,
    type: "Title",
    levelReq: null,
    classReq: null,
    specialReq: null,
    rarity: "Rare",
  },
  {
    id: 63,
    name: "Druid",
    description: null,
    icon: "dice_druid",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: null,
    classReq: "Druid",
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 64,
    name: "Barbarian",
    description: null,
    icon: "dice_barbarian",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: null,
    classReq: "Barbarian",
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 65,
    name: "Wizard",
    description: null,
    icon: "dice_wizard",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: null,
    classReq: "Wizard",
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 66,
    name: "Bard",
    description: null,
    icon: "dice_bard",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: null,
    classReq: "Bard",
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 67,
    name: "Warlock",
    description: null,
    icon: "dice_warlock",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: null,
    classReq: "Warlock",
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 68,
    name: "Fighter",
    description: null,
    icon: "dice_fighter",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: null,
    classReq: "Fighter",
    specialReq: null,
    rarity: "Common",
  },
  {
    id: 69,
    name: "Black_Sun",
    description: null,
    icon: "dice_black_sun",
    price: 5,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: null,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 10,
    rarity: "Epic",
  },
  {
    id: 70,
    name: "Fire",
    description: null,
    icon: "dice_fire",
    price: 3,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 3,
    rarity: "Epic",
  },
  {
    id: 71,
    name: "Ice",
    description: null,
    icon: "dice_ice",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 3,
    rarity: "Epic",
  },
  {
    id: 72,
    name: "Poison",
    description: null,
    icon: "dice_poison",
    price: 2,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: null,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 5,
    rarity: "Epic",
  },
  {
    id: 73,
    name: "Acid",
    description: null,
    icon: "dice_acid",
    price: 2,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 74,
    name: "Thunder",
    description: null,
    icon: "dice_thunder",
    price: 2,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 75,
    name: "Lightning",
    description: null,
    icon: "dice_lightning",
    price: 3,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 76,
    name: "Ghost",
    description: null,
    icon: "dice_ghost",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 77,
    name: "Water",
    description: null,
    icon: "dice_water",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 78,
    name: "Earth",
    description: null,
    icon: "dice_earth",
    price: 1,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 5,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 79,
    name: "Force",
    description: null,
    icon: "dice_force",
    price: 2,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 80,
    name: "Psychic",
    description: null,
    icon: "dice_psychic",
    price: 2,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 81,
    name: "Necrotic",
    description: null,
    icon: "dice_necrotic",
    price: 10,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 40,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 20,
    rarity: "Legendary",
  },
  {
    id: 82,
    name: "Pink_Dreams",
    description: null,
    icon: "dice_pink_dreams",
    price: 20,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 40,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 30,
    rarity: "Legendary",
  },
  {
    id: 83,
    name: "Inspired",
    description: null,
    icon: "dice_inspired",
    price: 4,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 84,
    name: "Bloodmoon",
    description: null,
    icon: "dice_bloodmoon",
    price: 2,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 4,
    rarity: "Rare",
  },
  {
    id: 85,
    name: "Starry_Night",
    description: null,
    icon: "dice_starry_night",
    price: 3,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 86,
    name: "Glitterparty",
    description: null,
    icon: "dice_glitterparty",
    price: 3,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 2,
    rarity: "Rare",
  },
  {
    id: 87,
    name: "Astral_Sea",
    description: null,
    icon: "dice_astral_sea",
    price: 2,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 2,
    rarity: "Rare",
  },
  {
    id: 88,
    name: "Bronze",
    description: null,
    icon: "dice_bronze",
    price: 4,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 15,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 2,
    rarity: "Epic",
  },
  {
    id: 89,
    name: "Dragons",
    description: null,
    icon: "dice_dragons",
    price: 7,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 30,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 5,
    rarity: "Epic",
  },
  {
    id: 90,
    name: "Birdup",
    description: null,
    icon: "dice_birdup",
    price: 7,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 40,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 8,
    rarity: "Epic",
  },
  {
    id: 91,
    name: "Tiger_King",
    description: null,
    icon: "dice_tiger_king",
    price: 15,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 50,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 20,
    rarity: "Legendary",
  },
  {
    id: 92,
    name: "Rainbow",
    description: null,
    icon: "dice_rainbow",
    price: 7,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 25,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 10,
    rarity: "Legendary",
  },
  {
    id: 93,
    name: "Kuro",
    description: null,
    icon: "dice_kuro",
    price: 20,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 80,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 50,
    rarity: "Legendary",
  },
  {
    id: 94,
    name: "Default",
    description: null,
    icon: "dice_default",
    price: 1000,
    currency: "GOLD",
    type: "DiceColorset",
    levelReq: null,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Common",
  },
  {
    id: 95,
    name: "Gold",
    description: null,
    icon: "dice_gold",
    price: 100000,
    currency: "GOLD",
    type: "DiceColorset",
    levelReq: 40,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Epic",
  },
  {
    id: 96,
    name: "Silver",
    description: null,
    icon: "dice_silver",
    price: 50000,
    currency: "GOLD",
    type: "DiceColorset",
    levelReq: 40,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Common",
  },
  {
    id: 97,
    name: "Hollow",
    description: null,
    icon: "dice_hollow",
    price: 2,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 10,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: null,
    rarity: "Rare",
  },
  {
    id: 98,
    name: "Shiro",
    description: null,
    icon: "dice_shiro",
    price: 20,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 65,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 40,
    rarity: "Legendary",
  },
  {
    id: 99,
    name: "Primordial",
    description: null,
    icon: "dice_primordial",
    price: 30,
    currency: "GEMSTONES",
    type: "DiceColorset",
    levelReq: 100,
    classReq: null,
    specialReq: null,
    gemstonesSpentReq: 100,
    rarity: "Mythic",
  },
];

export default shopItems;
