export const oldDiceSettings = {
  container: "#dice-canvas", // required
  assetPath: "/assets/", // required
  themeColor: "#581c87",
  scale: 6,
  gravity: 0.5,
  restitution: 0.3,
  settleTimeout: 6000,
};

export const colorsets = {
  coin_default: {
    name: "Gold Coin",
    description: "Gold Dragonhead Coin",
    category: "Other",
    foreground: "#f6c928",
    background: "#f6c928",
    outline: "none",
    texture: "metal",
  },
  coin_silver: {
    name: "Silver Coin",
    description: "Gold Dragonhead Coin",
    category: "Other",
    foreground: "#f6c928",
    background: "#f6c928",
    outline: "none",
    texture: "metal",
  },
  radiant: {
    name: "Radiant",
    category: "Damage Types",
    foreground: "#F9B333",
    background: "#FFFFFF",
    outline: "",
    texture: "paper",
    description: "Radiant",
  },
  fire: {
    name: "Fire",
    category: "Damage Types",
    foreground: "#f8d84f",
    background: ["#f8d84f", "#f9b02d", "#f43c04", "#910200", "#4c1009"],
    outline: "black",
    texture: "fire",
    description: "Fire",
  },
  ice: {
    name: "Ice",
    category: "Damage Types",
    foreground: "#60E9FF",
    background: ["#214fa3", "#3c6ac1", "#253f70", "#0b56e2", "#09317a"],
    outline: "black",
    texture: "ice",
    description: "Ice",
  },
  poison: {
    name: "Poison",
    category: "Damage Types",
    foreground: "#D6A8FF",
    background: ["#313866", "#504099", "#66409e", "#934fc3", "#c949fc"],
    outline: "black",
    texture: "cloudy",
    description: "Poison",
  },
  acid: {
    name: "Acid",
    category: "Damage Types",
    foreground: "#A9FF70",
    background: [
      "#a6ff00",
      "#83b625",
      "#5ace04",
      "#69f006",
      "#b0f006",
      "#93bc25",
    ],
    outline: "black",
    texture: "marble",
    description: "Acid",
  },
  thunder: {
    name: "Thunder",
    category: "Damage Types",
    foreground: "#FFC500",
    background: "#7D7D7D",
    outline: "black",
    texture: "cloudy",
    description: "Thunder",
  },
  lightning: {
    name: "Lightning",
    category: "Damage Types",
    foreground: "#FFC500",
    background: ["#f17105", "#f3ca40", "#eddea4", "#df9a57", "#dea54b"],
    outline: "#7D7D7D",
    texture: "ice",
    description: "Lightning",
  },
  air: {
    name: "Air",
    category: "Damage Types",
    foreground: "#ffffff",
    background: ["#d0e5ea", "#c3dee5", "#a4ccd6", "#8dafb7", "#80a4ad"],
    outline: "black",
    texture: "cloudy",
    description: "Air",
  },
  water: {
    name: "Water",
    category: "Damage Types",
    foreground: "#60E9FF",
    background: ["#87b8c4", "#77a6b2", "#6b98a3", "#5b8691", "#4b757f"],
    outline: "black",
    texture: "water",
    description: "Water",
  },
  earth: {
    name: "Earth",
    category: "Damage Types",
    foreground: "#6C9943",
    background: [
      "#346804",
      "#184200",
      "#527f22",
      "#3a1d04",
      "#56341a",
      "#331c17",
      "#5a352a",
      "#302210",
    ],
    outline: "black",
    texture: "speckles",
    description: "Earth",
  },
  force: {
    name: "Force",
    category: "Damage Types",
    foreground: "white",
    background: ["#FF97FF", "#FF68FF", "#C651C6"],
    outline: "#570000",
    texture: "stars",
    description: "Force",
  },
  psychic: {
    name: "Psychic",
    category: "Damage Types",
    foreground: "#D6A8FF",
    background: [
      "#313866",
      "#504099",
      "#66409E",
      "#934FC3",
      "#C949FC",
      "#313866",
    ],
    outline: "black",
    texture: "speckles",
    description: "Psychic",
  },
  necrotic: {
    name: "Necrotic",
    category: "Damage Types",
    foreground: "#ffffff",
    background: "#6F0000",
    outline: "black",
    texture: "skulls",
    description: "Necrotic",
  },
  pinkdreams: {
    name: "Pink Dreams",
    category: "Custom Sets",
    foreground: "white",
    background: ["#ff007c", "#df73ff", "#f400a1", "#df00ff", "#ff33cc"],
    outline: "#570000",
    texture: "skulls",
    description: "Pink Dreams, for Ethan",
  },
  inspired: {
    name: "Inspired",
    category: "Custom Sets",
    foreground: "#FFD800",
    background: "#C4C4B6",
    outline: "#8E8E86",
    texture: "none",
    description: "Inspired, for Austin",
  },
  bloodmoon: {
    name: "Blood Moon",
    category: "Custom Sets",
    foreground: "#CDB800",
    background: "#6F0000",
    outline: "black",
    texture: "marble",
    description: "Blood Moon, for Jared",
  },
  starynight: {
    name: "Stary Night",
    category: "Custom Sets",
    foreground: "#4F708F",
    background: ["#091636", "#233660", "#4F708F", "#8597AD", "#E2E2E2"],
    outline: "white",
    texture: "speckles",
    description: "Stary Night, for Mai",
  },
  glitterparty: {
    name: "Glitter Party",
    category: "Custom Sets",
    foreground: "white",
    background: ["#FFB5F5", "#7FC9FF", "#A17FFF"],
    outline: "none",
    texture: "glitter",
    description: "Glitter Party, for Austin",
  },
  astralsea: {
    name: "Astral Sea",
    category: "Custom Sets",
    foreground: "#565656",
    background: "white",
    outline: "none",
    texture: "astral",
    description: "The Astral Sea, for Austin",
  },
  bronze: {
    name: "Thylean Bronze",
    description: "Thylean Bronze by @SpencerThayer",
    category: "Custom Sets",
    foreground: ["#FF9159", "#FFB066", "#FFBF59", "#FFD059"],
    background: ["#705206", "#7A4E06", "#643100", "#7A2D06"],
    outline: ["#3D2D03", "#472D04", "#301700", "#471A04"],
    edge: ["#FF5D0D", "#FF7B00", "#FFA20D", "#FFBA0D"],
    texture: [
      "bronze01",
      "bronze02",
      "bronze03",
      "bronze03a",
      "bronze03b",
      "bronze04",
    ],
  },
  dragons: {
    name: "Here be Dragons",
    category: "Custom Sets",
    foreground: "#FFFFFF",
    // 			[ red,       black,     blue,      green      white      gold,      silver,    bronze,    copper     brass
    background: [
      "#B80000",
      "#4D5A5A",
      "#5BB8FF",
      "#7E934E",
      "#FFFFFF",
      "#F6ED7C",
      "#7797A3",
      "#A78437",
      "#862C1A",
      "#FFDF8A",
    ],
    outline: "black",
    texture: ["dragon", "lizard"],
    description: "Here be Dragons",
  },
  birdup: {
    name: "Bird Up",
    category: "Custom Sets",
    foreground: "#FFFFFF",
    background: [
      "#F11602",
      "#FFC000",
      "#6EC832",
      "#0094BC",
      "#05608D",
      "#FEABB3",
      "#F75680",
      "#F3F0DF",
      "#C7A57F",
    ],
    outline: "black",
    texture: "bird",
    description: "Bird Up!",
  },
  tigerking: {
    name: "Tiger King",
    category: "Other",
    foreground: "#ffffff",
    background: "#FFCC40",
    outline: "black",
    texture: ["leopard", "tiger", "cheetah"],
    description: "Leopard Print",
  },
  rainbow: {
    name: "Rainblow",
    category: "Colors",
    foreground: [
      "#FF5959",
      "#FFA74F",
      "#FFFF56",
      "#59FF59",
      "#2374FF",
      "#00FFFF",
      "#FF59FF",
    ],
    background: [
      "#900000",
      "#CE3900",
      "#BCBC00",
      "#00B500",
      "#00008E",
      "#008282",
      "#A500A5",
    ],
    outline: "black",
    texture: "none",
    description: "Rainblow",
  },
  black: {
    name: "Black",
    category: "Colors",
    foreground: "#ffffff",
    background: "#000000",
    outline: "black",
    texture: "none",
    description: "Black",
  },
  white: {
    name: "White",
    category: "Colors",
    foreground: "#000000",
    background: "#FFFFFF",
    outline: "#FFFFFF",
    texture: "none",
    description: "White",
  },
};

export const diceSettings: DiceSettings = {
  framerate: 1 / 60, // 60fps
  sounds: false,
  color_spotlight: "#ffffff",
  shadows: true,
  theme_customColorset: {
    background: "#581c87",
    foreground: "#ffffff",
    outline: "black",
    texture: "marble",
    material: "plastic",
  },
  assetPath: "/assets/",
  light_intensity: 0.7,
  gravity_multiplier: 200,
  baseScale: 150,
  strength: 2, // toss strength of dice
};
