// export const oldDiceSettings = {
//   container: "#dice-canvas", // required
//   assetPath: "/assets/", // required
//   themeColor: "#581c87",
//   scale: 6,
//   gravity: 0.5,
//   restitution: 0.3,
//   settleTimeout: 6000,
// };

export const diceSettings: DiceSettings = {
  framerate: 1 / 60, // 60fps
  sounds: false,
  color_spotlight: "#ffffff",
  shadows: true,
  theme_customColorset: {
    background: "#ffffff",
    foreground: "#000000",
    outline: "black",
    texture: "none",
    material: "plastic",
    edge: "black",
  },
  assetPath: "/assets/",
  light_intensity: 0.9,
  gravity_multiplier: 200,
  baseScale: 150,
  strength: 2, // toss strength of dice
};

export const colorsets: { [key: string]: diceColorset } = {
  Default: {
    background: "#ffffff",
    foreground: "#000000",
    outline: "black",
    texture: "none",
    edge: "black",
  },
  // blue
  Wizard: {
    foreground: "#70C8FF",
    background: "#003366",
    outline: "black",
    texture: "marble",
    edge: "#0055AA",
  },
  Warlock: {
    foreground: "#FF5959",
    background: "#900000",
    outline: "black",
    texture: "marble",
    edge: "#CE3900",
  },
  // orange black
  Barbarian: {
    foreground: "#ffffff",
    background: "#331900",
    outline: "black",
    texture: "fire",
  },
  Fighter: {
    foreground: "#ffffff",
    background: "#421407",
    outline: "black",
    texture: "wood",
  },
  Druid: {
    foreground: "#FFCC40",
    background: "#003300",
    outline: "black",
    texture: "metal",
    edge: "#007700",
  },
  Bard: {
    foreground: ["#ffffff", "#000000"],
    background: ["#cc0000", "#ffffff"],
    outline: "black",
    texture: "paper",
    edge: "black",
  },
  Black_Sun: {
    foreground: "#FFCC40",
    background: "#000000",
    outline: "black",
    texture: "metal",
    edge: "#FF7B00",
  },
  Coin: {
    foreground: "#f6e27f",
    background: "#f6c928",
    // edge: "#b8860b",
    // outline: "#ffffff",
    texture: "metal",
  },
  Silver: {
    foreground: "#c0c0c0",
    background: "#ffffff",
    outline: "none",
    texture: "metal",
  },
  Hollow: {
    foreground: "#ffffff",
    background: "#ffffff",
    outline: "black",
    texture: "stars",
  },
  Fire: {
    foreground: "#f8d84f",
    background: ["#f8d84f", "#f9b02d", "#f43c04", "#910200", "#4c1009"],
    outline: "black",
    texture: "fire",
  },
  Ice: {
    foreground: "#60E9FF",
    background: ["#214fa3", "#3c6ac1", "#253f70", "#0b56e2", "#09317a"],
    outline: "black",
    texture: "ice",
  },
  Poison: {
    foreground: "#D6A8FF",
    background: ["#313866", "#504099", "#66409e", "#934fc3", "#c949fc"],
    outline: "black",
    texture: "cloudy",
  },
  Acid: {
    foreground: "#A9FF70",
    background: [
      "#a6ff00",
      "#83b625",
      "#5ace04",
      "#69f006",
      "#b0f006",
      "#93bc25",
    ],
    outline: "black",
    texture: "marble",
  },
  Thunder: {
    foreground: "#FFC500",
    background: "#7D7D7D",
    outline: "black",
    texture: "cloudy",
  },
  Lightning: {
    foreground: "#FFC500",
    background: ["#f17105", "#f3ca40", "#eddea4", "#df9a57", "#dea54b"],
    outline: "#7D7D7D",
    texture: "ice",
  },
  Ghost: {
    foreground: "#ffffff",
    background: ["#d0e5ea", "#c3dee5", "#a4ccd6", "#8dafb7", "#80a4ad"],
    outline: "black",
    texture: "cloudy",
  },
  Water: {
    foreground: "#60E9FF",
    background: ["#87b8c4", "#77a6b2", "#6b98a3", "#5b8691", "#4b757f"],
    outline: "black",
    texture: "water",
  },
  Earth: {
    foreground: "#6C9943",
    background: [
      "#346804",
      "#184200",
      "#527f22",
      "#3a1d04",
      "#56341a",
      "#331c17",
      "#5a352a",
      "#302210",
    ],
    outline: "black",
    texture: "speckles",
  },
  Force: {
    foreground: "white",
    background: ["#FF97FF", "#FF68FF", "#C651C6"],
    outline: "#570000",
    texture: "stars",
  },
  Psychic: {
    foreground: "#D6A8FF",
    background: [
      "#313866",
      "#504099",
      "#66409E",
      "#934FC3",
      "#C949FC",
      "#313866",
    ],
    outline: "black",
    texture: "speckles",
  },
  Necrotic: {
    foreground: "#ffffff",
    background: "#6F0000",
    outline: "black",
    texture: "skulls",
  },
  Pink_Dreams: {
    foreground: "white",
    background: ["#ff007c", "#df73ff", "#f400a1", "#df00ff", "#ff33cc"],
    outline: "#570000",
    texture: "skulls",
  },
  Inspired: {
    foreground: "#4C4C3E",
    background: "#C4C4B6",
    outline: "#ffffff",
    texture: "bronze03b",
  },
  Bloodmoon: {
    foreground: "#CDB800",
    background: "#6F0000",
    outline: "black",
    texture: "marble",
  },
  Starry_Night: {
    foreground: "#ffffff",
    background: ["#091636", "#233660", "#4F708F", "#8597AD", "#E2E2E2"],
    outline: "black",
    texture: "speckles",
  },
  Glitterparty: {
    foreground: "white",
    background: ["#FFB5F5", "#7FC9FF", "#A17FFF"],
    outline: "none",
    texture: "glitter",
  },
  Astral_Sea: {
    foreground: "#565656",
    background: "white",
    outline: "none",
    texture: "astral",
  },
  Bronze: {
    foreground: ["#FF9159", "#FFB066", "#FFBF59", "#FFD059"],
    background: ["#705206", "#7A4E06", "#643100", "#7A2D06"],
    outline: ["#3D2D03", "#472D04", "#301700", "#471A04"],
    edge: ["#FF5D0D", "#FF7B00", "#FFA20D", "#FFBA0D"],
    texture: [
      "bronze01",
      "bronze02",
      "bronze03",
      "bronze03a",
      "bronze03b",
      "bronze04",
    ],
  },
  Dragons: {
    foreground: "#FFFFFF",
    // 			[ red,       black,     blue,      green      white      gold,      silver,    bronze,    copper     brass
    background: [
      "#B80000",
      "#4D5A5A",
      "#5BB8FF",
      "#7E934E",
      "#FFFFFF",
      "#F6ED7C",
      "#7797A3",
      "#A78437",
      "#862C1A",
      "#FFDF8A",
    ],
    outline: "black",
    texture: ["dragon", "lizard"],
  },
  Birdup: {
    foreground: "#FFFFFF",
    background: [
      "#F11602",
      "#FFC000",
      "#6EC832",
      "#0094BC",
      "#05608D",
      "#FEABB3",
      "#F75680",
      "#F3F0DF",
      "#C7A57F",
    ],
    outline: "black",
    texture: "bird",
  },
  Tiger_King: {
    foreground: "#ffffff",
    background: "#FFCC40",
    outline: "black",
    texture: ["leopard", "tiger", "cheetah"],
  },
  Rainbow: {
    foreground: [
      "#FF5959",
      "#FFA74F",
      "#FFFF56",
      "#59FF59",
      "#2374FF",
      "#00FFFF",
      "#FF59FF",
    ],
    background: [
      "#900000",
      "#CE3900",
      "#BCBC00",
      "#00B500",
      "#00008E",
      "#008282",
      "#A500A5",
    ],
    outline: "black",
    texture: "metal",
  },
  Kuro: {
    foreground: "#ffffff",
    background: "#000000",
    outline: "black",
    texture: "ice",
  },
  Shiro: {
    foreground: "#000000",
    background: "#FFFFFF",
    outline: "#FFFFFF",
    texture: "ice",
  },
  Primordial: {
    foreground: "#000000",
    background: ["#FFFFFF"],
    outline: "#ffffff",
    texture: "skulls",
  },
};
